"""Change security_id to String in holdings and transactions

Revision ID: 797176349341
Revises: 5370c48333b2
Create Date: 2024-07-07 17:22:29.006813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797176349341'
down_revision = '5370c48333b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('security_id',
               existing_type=sa.Integer(),
               type_=sa.String(length=10),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('security_id',
               existing_type=sa.Integer(),
               type_=sa.String(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('security_id',
               existing_type=sa.String(length=10),
               type_=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('security_id',
               existing_type=sa.String(length=10),
               type_=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###
